"""The embedded DCS type set loads and stays in sync with the vendored Lua set."""

import re
from pathlib import Path

import pytest

from ctld_tools.datamine import known_dcs_types, spawn_category, type_category

REPO = Path(__file__).resolve().parents[3]
LUA_SET = REPO / "tests" / "data" / "dcs_types.lua"


def test_known_types_loads_nonempty():
    types = known_dcs_types()
    assert len(types) > 1000
    assert "M-1 Abrams" in types
    assert "Ural-375" in types


def test_embedded_json_matches_vendored_lua():
    """The package JSON must equal the type set in tests/data/dcs_types.lua
    (both generated by gen_dcs_types.py from the same datamine ref)."""
    lua_types = set(re.findall(r'\["([^"]+)"\]\s*=\s*true', LUA_SET.read_text(encoding="utf-8")))
    assert known_dcs_types() == frozenset(lua_types)


# ── Categories: what resolves `spawnAs: AIR` to what the engine expects ─────────
# FEAT-EDITOR-COVERAGE ticket 01. The datamine layout is <Category>/<Type>/<TypeName>.lua and the
# generator used to discard the category. DCS needs the right Group.Category at spawn, and nothing
# in src/ can ask for it, so the tool resolves it at authoring time.


def test_every_type_carries_a_category():
    from ctld_tools.datamine import _types

    uncategorised = [name for name, cat in _types().items() if not cat]
    assert uncategorised == []


@pytest.mark.parametrize(
    ("unit", "expected"),
    [
        ("UH-1H", "HELICOPTER"),
        ("Mi-8MT", "HELICOPTER"),
        ("MQ-9 Reaper", "AIRPLANE"),  # a drone: an aeroplane as far as DCS is concerned
        ("RQ-1A Predator", "AIRPLANE"),
        ("Hummer", "GROUND"),
        ("Ural-375", "GROUND"),
    ],
)
def test_spawn_category_resolves_the_air_convenience(unit, expected):
    assert spawn_category(unit) == expected


def test_an_unknown_type_resolves_to_ground_rather_than_guessing():
    """`validate` reports an unknown unit separately; this must not invent an aircraft."""
    assert type_category("NotAUnit") is None
    assert spawn_category("NotAUnit") == "GROUND"


def test_the_two_shipped_drones_resolve_to_what_the_catalogue_carries():
    """The catalogue says AIRPLANE for both; the resolver must agree, or a round-trip would drift."""
    for drone in ("MQ-9 Reaper", "RQ-1A Predator"):
        assert spawn_category(drone) == "AIRPLANE"
