"""The embedded DCS type set loads and stays in sync with the vendored Lua set."""

import re
from pathlib import Path

from ctld_tools.datamine import known_dcs_types

REPO = Path(__file__).resolve().parents[3]
LUA_SET = REPO / "tests" / "data" / "dcs_types.lua"


def test_known_types_loads_nonempty():
    types = known_dcs_types()
    assert len(types) > 1000
    assert "M-1 Abrams" in types
    assert "Ural-375" in types


def test_embedded_json_matches_vendored_lua():
    """The package JSON must equal the type set in tests/data/dcs_types.lua
    (both generated by gen_dcs_types.py from the same datamine ref)."""
    lua_types = set(re.findall(r'\["([^"]+)"\]\s*=\s*true', LUA_SET.read_text(encoding="utf-8")))
    assert known_dcs_types() == frozenset(lua_types)
