"""Wrap a config YAML verbatim into a Lua string module.

The runtime never parses a Lua *table* of defaults any more (ADR 0011): it reads a YAML
string from `ctld.configDefault` (engine defaults, embedded by the build) or
`ctld.configUser` (a Mission Maker's snapshot, exported by the tool) and parses it in
Lua. Both are the *same* wrap — a `ctld.<var> = [[ ...yaml... ]]` module — so this one
function serves the build (configDefault) and the lot-3 MM export (configUser).

The long-bracket level (`[[`, `[=[`, `[==[`, …) is chosen dynamically so the closing
delimiter can never collide with the YAML content.
"""

from __future__ import annotations

from pathlib import Path

_HEADER = "-- GENERATED by ctld-tools (embed) — verbatim embed of a config YAML. DO NOT EDIT.\nctld = ctld or {}\n"


def _bracket_level(text: str) -> str:
    """Smallest run of '=' such that the closing delimiter is absent from `text`."""
    eq = ""
    while f"]{eq}]" in text:
        eq += "="
    return eq


def wrap(yaml_text: str, var: str = "configDefault") -> str:
    """Return a Lua module assigning `yaml_text` verbatim to `ctld.<var>` as a string."""
    eq = _bracket_level(yaml_text)
    return f"{_HEADER}ctld.{var} = [{eq}[\n{yaml_text}]{eq}]\n"


def wrap_file(yaml_path: str | Path, out_path: str | Path, var: str = "configDefault") -> None:
    """Read a config YAML and write the wrapped Lua string module."""
    yaml_text = Path(yaml_path).read_text(encoding="utf-8")
    Path(out_path).write_text(wrap(yaml_text, var), encoding="utf-8", newline="\n")


def unwrap(lua_text: str, var: str = "configUser") -> str | None:
    """The YAML inside a `ctld.<var> = [==[ … ]==]` module, or None if there is none.

    The inverse of `wrap`, and it has to be: the bracket level is chosen from the content, so a
    fixed pattern would read `[[` correctly and truncate a `[==[` snapshot at the first `]]`
    appearing inside its own YAML. Finding the opening delimiter first, then its exact match, is
    what makes it safe.
    """
    import re

    opening = re.search(rf"ctld\.{re.escape(var)}\s*=\s*\[(=*)\[", lua_text)
    if not opening:
        return None
    eq = opening.group(1)
    body = lua_text[opening.end() :]
    end = body.find(f"]{eq}]")
    if end == -1:
        return None
    # `wrap` writes a newline right after the opening delimiter; drop it, keep everything else
    # verbatim — trailing blank lines included, since the YAML is the payload, not a document.
    return body[:end].lstrip("\n")
