"""One-shot extractor: CTLD_config.lua defaults -> ctld-config.yaml.

Runs the Lua defaults (via lupa) and writes a sectioned YAML source of truth.
The mm_facing/advanced split is for readability only — the generator merges the
two sections, so the boundary never affects parity.
"""

from __future__ import annotations

from pathlib import Path

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap

from ctld_tools.luaconfig import load_default_settings

# Technical / internal tuning constants → the "advanced" section. Everything else
# (crate catalogue, troops, zones, capabilities, gameplay switches) is mm_facing.
_ADVANCED_KEYS = frozenset(
    {
        # infantry weight model
        "SOLDIER_WEIGHT",
        "KIT_WEIGHT",
        "RIFLE_WEIGHT",
        "MANPAD_WEIGHT",
        "RPG_WEIGHT",
        "MG_WEIGHT",
        "MORTAR_WEIGHT",
        "JTAC_WEIGHT",
        "CIV_WEIGHT",
        # beacon internals
        "radioSound",
        "radioSoundFC3",
        "deployedBeaconBattery",
        "beaconAutoRefreshLayer",
        "beaconIconColor",
        "beaconIconRadius",
        "beaconLayerEnabled",
        "beaconRefreshInterval",
        "beaconTextSize",
        # parachute physics
        "parachuteDescentRateCrates",
        "parachuteDescentRateTroops",
        "parachuteDescentRateVehicles",
        "parachuteInertiaFactor",
        "parachuteLateralDriftMax",
        "parachuteLateralDriftMin",
        "autoUnpackRadiusParachute",
        "parachuteMinAltitudeCrates",
        "parachuteMinAltitudeTroops",
        "parachuteMinAltitudeVehicles",
        # hover physics
        "minimumHoverHeight",
        "maximumHoverHeight",
        "maxDistanceFromCrate",
        "hoverTime",
        "maxDropHeight",
        "groundAglThreshold",
        # JTAC internals
        "JTAC_smokeColour_BLUE",
        "JTAC_smokeColour_RED",
        "JTAC_smokeOn_BLUE",
        "JTAC_smokeOn_RED",
        "JTAC_smokeMarginOfError",
        "JTAC_smokeOffset_x",
        "JTAC_smokeOffset_y",
        "JTAC_smokeOffset_z",
        "JTAC_laseIntervalSeconds",
        "JTAC_searchIntervalSeconds",
        "JTAC_laseSpotCorrections",
        "JTAC_droneRadius",
        "JTAC_droneAltitude",
        "enableAutoOrbitingFlyingJtacOnTarget",
        "aaLaunchers",
        # 3D crate models
        "spawnableCratesModels",
        # debug / logging
        "debug",
        "debugScreenLog",
        "debugScreenLogDuration",
        "ctldLogPath",
        # misc tuning
        "crateSpacing",
        "spawnDistanceInCircle",
        "smokeAutoResume",
        "smokeAutoResumeInterval",
        "smokeRefreshInterval",
        "demineRadius",
        "modTypes",
    }
)


def sectionize(settings: dict) -> CommentedMap:
    """Split a flat settings dict into { mm_facing, advanced }, keys sorted."""
    mm_facing = CommentedMap()
    advanced = CommentedMap()
    for key in sorted(settings.keys(), key=str):
        target = advanced if key in _ADVANCED_KEYS else mm_facing
        target[key] = settings[key]
    doc = CommentedMap()
    doc["mm_facing"] = mm_facing
    doc["advanced"] = advanced
    return doc


def extract_file(config_lua_path: str | Path, out_yaml_path: str | Path) -> None:
    """Read CTLD_config.lua defaults and write the sectioned ctld-config.yaml."""
    src_dir = Path(config_lua_path).parent
    settings = load_default_settings(src_dir)
    doc = sectionize(settings)

    yaml = YAML()
    yaml.default_flow_style = False
    yaml.width = 4096  # avoid line-wrapping long lists
    with Path(out_yaml_path).open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(
            "# GENERATED by ctld-tools (extract) — the source of truth for CTLD engine defaults.\n"
            "# Sections mm_facing / advanced are for readability; the generator merges them.\n"
        )
        yaml.dump(doc, fh)
