"""Render the Lua defaults module from ctld-config.yaml.

The generated file defines `ctld.__configDefaults`, the table CTLDConfig:load()
copies into its settings. Deterministic output (sorted dict keys, arrays in
order). i18n fields (desc/name) are re-emitted as `ctld.tr("...")` — the only
non-literal construct in the CTLD defaults.
"""

from __future__ import annotations

from pathlib import Path

from ruamel.yaml import YAML

# Fields wrapped in ctld.tr() at generation time (see CTLD_config.lua: every
# desc/name is an i18n key, and there are no literal desc/name).
_I18N_FIELDS = frozenset({"desc", "name"})

_HEADER = (
    "-- GENERATED by ctld-tools (gen-config) — DO NOT EDIT.\n"
    "-- Source of truth: ctld-config.yaml. Regenerate via the build.\n"
    "ctld = ctld or {}\n"
    "ctld.__configDefaults = "
)


def _lua_str(value: str) -> str:
    """Quote a Python string as a Lua string literal."""
    escaped = (
        value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _lua_number(value) -> str:
    if isinstance(value, bool):  # bool is a subclass of int — handle first
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    # float: repr gives the shortest round-tripping decimal for an IEEE-754 double.
    return repr(value)


def _lua_key(key: str) -> str:
    """Render a table key: bare identifier when safe, else ["..."]."""
    if isinstance(key, str) and key.isidentifier():
        return key
    return f"[{_lua_str(key)}]" if isinstance(key, str) else f"[{key}]"


def _render_value(value, indent: int, field: str | None = None) -> str:
    if field in _I18N_FIELDS and isinstance(value, str):
        return f"ctld.tr({_lua_str(value)})"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return _lua_number(value)
    if isinstance(value, str):
        return _lua_str(value)
    if isinstance(value, list):
        return _render_list(value, indent)
    if isinstance(value, dict):
        return _render_dict(value, indent)
    raise TypeError(f"unsupported value type for Lua rendering: {type(value).__name__}")


def _render_list(items: list, indent: int) -> str:
    if not items:
        return "{}"
    pad = "    " * (indent + 1)
    inner = ",\n".join(pad + _render_value(v, indent + 1) for v in items)
    return "{\n" + inner + "\n" + "    " * indent + "}"


def _render_dict(table: dict, indent: int) -> str:
    if not table:
        return "{}"
    pad = "    " * (indent + 1)
    lines = []
    for key in sorted(table.keys(), key=str):
        rendered = _render_value(table[key], indent + 1, field=key if isinstance(key, str) else None)
        lines.append(
            f"{pad}[{_lua_str(key)}] = {rendered}"
            if not (isinstance(key, str) and key.isidentifier())
            else f"{pad}{key} = {rendered}"
        )
    return "{\n" + ",\n".join(lines) + "\n" + "    " * indent + "}"


def render(settings: dict) -> str:
    """Render the full generated-Lua text from a flat settings dict."""
    return _HEADER + _render_dict(settings, 0) + "\n"


def _load_yaml(path: Path) -> dict:
    yaml = YAML(typ="safe")
    with path.open("r", encoding="utf-8") as fh:
        doc = yaml.load(fh)
    # ctld-config.yaml is sectioned: merge mm_facing + advanced into a flat map.
    if isinstance(doc, dict) and set(doc.keys()) <= {"mm_facing", "advanced"}:
        merged: dict = {}
        for section in ("mm_facing", "advanced"):
            merged.update(doc.get(section) or {})
        return merged
    return doc


def generate_file(yaml_path: str | Path, out_path: str | Path) -> None:
    """Read ctld-config.yaml and write the generated Lua defaults module."""
    settings = _load_yaml(Path(yaml_path))
    text = render(settings)
    Path(out_path).write_text(text, encoding="utf-8", newline="\n")
