"""Compile a user-config.yaml into CTLD_userConfig.lua.

Scalars go into the `ctld.yamlConfigDatas` block (Section 1). Operations
(crates/troops/arrays) compile 1:1 into `ctld.userSetup` helper calls (Section 2).
Mission Makers target crates/troops by name; names are resolved to weights here,
against the reference catalogue, so the emitted runtime calls use the unique key.
"""

from __future__ import annotations

from pathlib import Path

from ctld_tools.genconfig import _lua_str, _render_value
from ctld_tools.reference import Reference
from ctld_tools.validate import has_errors, validate


class UserConfigError(Exception):
    def __init__(self, findings):
        self.findings = findings
        super().__init__("\n".join(str(f) for f in findings))


def _scalar_block(settings: dict) -> list[str]:
    if not settings:
        return []
    lines = ["ctld.yamlConfigDatas = [[", ""]
    for key in sorted(settings):
        lines.append(f"ctld.{key}: {settings[key]}")
    lines += ["", "]]", ""]
    return lines


def _crate_add_entry(entry: dict) -> dict:
    """Map a user 'add' entry to a runtime crate descriptor dict (name->desc, weight_kg->weight)."""
    out: dict = {}
    if "name" in entry:
        out["desc"] = entry["name"]
    weight = entry.get("weight_kg", entry.get("weight"))
    if weight is not None:
        out["weight"] = weight
    for k, v in entry.items():
        if k not in ("name", "weight_kg", "weight", "section"):
            out[k] = v
    return out


def _operations(cfg: dict, ref: Reference) -> list[str]:
    lines: list[str] = []
    crates = cfg.get("crates") or {}
    for entry in crates.get("add") or []:
        section = entry.get("section", "Support")
        desc = _render_value(_crate_add_entry(entry), 1)
        lines.append(f"    ctld.addCrate({_lua_str(section)}, {desc})")
    for target in crates.get("remove") or []:
        weight, _ = ref.resolve_crate(target)
        lines.append(f"    ctld.removeCrate({weight})  -- {target}")
    for entry in crates.get("patch") or []:
        target = entry.get("name", entry.get("weight"))
        weight, _ = ref.resolve_crate(target)
        # Map weight_kg -> weight (the runtime crate key), as _crate_add_entry does for add.
        patch = {("weight" if k == "weight_kg" else k): v for k, v in entry.items() if k not in ("name", "weight")}
        lines.append(f"    ctld.patchCrate({weight}, {_render_value(patch, 1)})  -- {target}")

    troops = cfg.get("troops") or {}
    for entry in troops.get("add") or []:
        lines.append(f"    ctld.addTroopGroup({_render_value(entry, 1)})")
    for name in troops.get("remove") or []:
        lines.append(f"    ctld.removeTroopGroup({_lua_str(name)})")
    for entry in troops.get("patch") or []:
        name = entry.get("name")
        patch = {k: v for k, v in entry.items() if k != "name"}
        lines.append(f"    ctld.patchTroopGroup({_lua_str(name)}, {_render_value(patch, 1)})")

    for setting, items in (cfg.get("arrays") or {}).items():
        for item in items:
            lines.append(f"    ctld.addTo({_lua_str(setting)}, {_render_value(item, 1)})")
    return lines


def render_user_config(cfg: dict, ref: Reference) -> str:
    """Render CTLD_userConfig.lua from a validated user-config dict."""
    findings = validate(cfg, ref)
    if has_errors(findings):
        raise UserConfigError([f for f in findings if f.severity == "error"])

    lines = [
        "-- CTLD_userConfig.lua — GENERATED by ctld-tools (gen-user).",
        "-- Load BEFORE CTLD.lua in the mission (MISSION START → DO SCRIPT FILE).",
        "if ctld == nil then ctld = {} end",
        "",
    ]
    lines += _scalar_block(cfg.get("settings") or {})
    ops = _operations(cfg, ref)
    if ops:
        lines += [
            "ctld.userSetup = ctld.userSetup or {}",
            "table.insert(ctld.userSetup, function(cfg)",
            *ops,
            "end)",
            "",
        ]
    return "\n".join(lines) + "\n"


def generate_user_file(yaml_path: str | Path, out_path: str | Path, src: str | Path | None = None) -> None:
    from ctld_tools.validate import load_user_config

    cfg = load_user_config(yaml_path)
    ref = Reference.from_src(src) if src else Reference.from_embedded()
    Path(out_path).write_text(render_user_config(cfg, ref), encoding="utf-8", newline="\n")
