# build_companion.ps1 - Build the optional dev-time asset-check companion.
# Output: dist/CTLD_asset_check.lua in UTF-8 WITHOUT BOM (DCS Lua engine requirement).
#
# The companion = the vendored datamine stock-type set (as a global `_CTLD_STOCK_TYPES`) + the
# validator (tools/companion/asset_check.lua). A mission maker loads it from a MISSION START trigger
# AFTER CTLD during development; it WARNs on configured DCS types that are neither stock nor a
# declared mod type. It is NOT shipped in CTLD.lua and NOT meant for production missions.
#
# Usage: powershell -ExecutionPolicy Bypass -File tools/companion/build_companion.ps1

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot  = Resolve-Path (Join-Path $scriptDir "..\..")
$dataFile  = Join-Path $repoRoot "tests\data\dcs_types.lua"
$validator = Join-Path $scriptDir "asset_check.lua"
$distDir   = Join-Path $repoRoot "dist"
$outFile   = Join-Path $distDir "CTLD_asset_check.lua"
$utf8NoBOM = [System.Text.UTF8Encoding]::new($false)

if (-not (Test-Path $dataFile))  { throw "Missing datamine set: $dataFile" }
if (-not (Test-Path $validator)) { throw "Missing validator: $validator" }
if (-not (Test-Path $distDir))   { New-Item -ItemType Directory -Path $distDir | Out-Null }

# Turn the datamine set's `return { … }` into an assignment to a global the validator reads.
$data = [System.IO.File]::ReadAllText($dataFile)
$data = [regex]::Replace($data, 'return\s*\{', '_CTLD_STOCK_TYPES = {', 1)

$buildDate = (Get-Date).ToString("yyyy-MM-dd")
$sb = [System.Text.StringBuilder]::new()
$null = $sb.AppendLine('---@diagnostic disable')
$null = $sb.AppendLine('--[[')
$null = $sb.AppendLine('    CTLD asset-check companion (DEV-TIME ONLY — do not ship in production missions)')
$null = $sb.AppendLine("    Built : $buildDate")
$null = $sb.AppendLine('    Load from a MISSION START trigger AFTER CTLD.lua during development.')
$null = $sb.AppendLine('    WARNs on configured DCS types that are neither stock nor a declared mod. No spawning.')
$null = $sb.AppendLine('    DO NOT EDIT - generated by tools/companion/build_companion.ps1')
$null = $sb.AppendLine(']]')
$null = $sb.AppendLine('')
$null = $sb.AppendLine('-- ==== datamine stock-type set ====')
$null = $sb.AppendLine($data)
$null = $sb.AppendLine('-- ==== validator ====')
$null = $sb.AppendLine([System.IO.File]::ReadAllText($validator))

[System.IO.File]::WriteAllText($outFile, $sb.ToString(), $utf8NoBOM)
$size = (Get-Item $outFile).Length
Write-Host "Built dist/CTLD_asset_check.lua ($size bytes)"

$bytes = [System.IO.File]::ReadAllBytes($outFile)
if ($bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) { throw "BOM detected in $outFile" }
Write-Host "OK - no BOM."
