-- ============================================================
-- CTLD_userConfig.lua — optional mission configuration
--
-- HOW TO USE
--   In the Mission Editor add a trigger "MISSION START -> DO SCRIPT FILE" and select
--   this file BEFORE the CTLD.lua trigger. This file is optional: if omitted, CTLD
--   starts with its built-in factory defaults.
--
-- MODEL (ADR 0011)
--   Provide a COMPLETE configuration snapshot as a YAML string in ctld.configUser.
--   It fully REPLACES the engine defaults — there is no merge. An element you omit is
--   absent at runtime (not defaulted). A malformed snapshot is a hard error, so
--   generate and edit it with the CTLD config tool: it starts from the current
--   defaults (so nothing is lost by accident) and validates before export.
--
--   The YAML is the same format as the engine's CTLD_config.yaml: a configVersion tag,
--   the mm_facing / advanced sections, and the spawnableCrates / loadableGroups / zones
--   catalogue. The configVersion lets the tool detect a version gap on a CTLD upgrade.
-- ============================================================

if ctld == nil then ctld = {} end

-- Uncomment and paste your complete snapshot between the [[ and ]] long-bracket markers.
-- (Use a higher bracket level, e.g. [==[ ... ]==], if your text ever contains ]].)
--
-- ctld.configUser = [[
-- configVersion: "2.0.0"
-- mm_facing:
--   numberOfTroops: 10
--   # ... every mm-facing setting and catalogue section ...
-- advanced:
--   # ... every advanced setting ...
-- ]]
